// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Tx6ojepm8nHHUNP3lNtyU7tLkWxFCF4',
    appId: '1:558812065365:web:bbcfeae25f839aa51d6edc',
    messagingSenderId: '558812065365',
    projectId: 'smart-komplek',
    authDomain: 'smart-komplek.firebaseapp.com',
    storageBucket: 'smart-komplek.firebasestorage.app',
    measurementId: 'G-Q2HXQDWSNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNvwauI079QJzaqOr7qsNP9jP95505YLw',
    appId: '1:558812065365:android:d5afd6ebf16494a71d6edc',
    messagingSenderId: '558812065365',
    projectId: 'smart-komplek',
    storageBucket: 'smart-komplek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33pcgUgsT4XxIiTzIEP7sKopAkDw1okc',
    appId: '1:558812065365:ios:b18c4497b6b259591d6edc',
    messagingSenderId: '558812065365',
    projectId: 'smart-komplek',
    storageBucket: 'smart-komplek.firebasestorage.app',
    iosBundleId: 'com.example.smartKomplek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA33pcgUgsT4XxIiTzIEP7sKopAkDw1okc',
    appId: '1:558812065365:ios:b18c4497b6b259591d6edc',
    messagingSenderId: '558812065365',
    projectId: 'smart-komplek',
    storageBucket: 'smart-komplek.firebasestorage.app',
    iosBundleId: 'com.example.smartKomplek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Tx6ojepm8nHHUNP3lNtyU7tLkWxFCF4',
    appId: '1:558812065365:web:5abcbe2a3f5bc6d61d6edc',
    messagingSenderId: '558812065365',
    projectId: 'smart-komplek',
    authDomain: 'smart-komplek.firebaseapp.com',
    storageBucket: 'smart-komplek.firebasestorage.app',
    measurementId: 'G-DSED0G5NBF',
  );
}
